### ISSUE TITLE
add a Makefile

### ISSUE THREAD

**Issue by pmlopes** [jaymine/TCP-eventbus-client-C#1]
You should have a makefile in the root so we can build the project and document how you build it on windows.

**Comment by pmlopes** [comment]
For windows you can rely on vscode for example, see this SO question and responses:

http://stackoverflow.com/questions/30269449/how-do-i-set-up-vscode-to-compile-c-code

https://blogs.msdn.microsoft.com/vcblog/2016/03/31/cc-extension-for-visual-studio-code/

**Comment by jaymine** [comment]
Added Makefile
